{{- if .Values.bootstrapJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-bootstrap-config
data:
  workload_scheduler_agent_bootstrap_config.yaml: |-
{{ .Files.Get "config/workload_scheduler_agent_bootstrap_config.yaml" | indent 4 }}
  workload_scheduler_agent.yaml: |-
{{ .Files.Get "config/workload_scheduler_agent.yaml" | indent 4 }}
{{- end }}