{{- if .Values.bootstrapJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-bootstrap-config
data:
  intellimagic_agent_bootstrap_config.yaml: |-
{{ .Files.Get "config/intellimagic_agent_bootstrap_config.yaml" | indent 4 }}
  intellimagic_agent.yaml: |-
{{ .Files.Get "config/intellimagic_agent.yaml" | indent 4 }}
{{- end }}