{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  annotations:
    {{- include "wxa4z.annotations" . | nindent 4 }}
spec:
  {{- with .Values.pvc.accessModes}}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClass }}
  volumeMode: Filesystem
{{- end }}
