{{- if .Values.bootstrapJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-bootstrap-config
data:
  omegamon_insights_agent_bootstrap_config.yaml: |-
{{ .Files.Get "config/omegamon_insights_agent_bootstrap_config.yaml" | indent 4 }}
  omegamon_insights_agent.yaml: |-
{{ .Files.Get "config/omegamon_insights_agent.yaml" | indent 4 }}
{{- end }}